os:
  - osx
language: generic
install:
  - npm ci
script:
  - npm test
cache:
  directories:
    - 'node_modules'
before_install:
  - nvm install 12.16.2
  - nvm use 12.16.2
  - pyenv install 3.7.1
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - echo "[default]" >> ~/.aws/config
  - echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
  - echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
after_success:
  - npm run aws:upload
