os:
  - osx
language: generic
install:
  - npm ci
script:
  - npm test
cache:
  directories:
    - 'node_modules'
    - $HOME/.cache/python
    - $HOME/.cache/pip
before_install:
  - nvm install 12.16.2
  - nvm use 12.16.2
  - pip install -U pip
  - pip install awscli
  - mkdir ~/.aws
  - echo "[default]" >> ~/.aws/config
  - echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
  - echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
after_success:
  - npm run aws:upload
