os:
  - osx
language: generic
dist: xenial
addons:
  snaps:
    - name: aws-cli
install:
  - npm ci
script:
  - npm test
before_install:
  - mkdir ~/.aws
  - echo "[default]" >> ~/.aws/config
  - echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
  - echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
after_success:
  - npm run aws:upload
