os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '12'
cache:
  directories:
    - 'node_modules'
before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
after_success:
  - npm run aws:package
