os:
  - osx
language: node_js
node_js:
  - '12'
cache:
  directories:
    - 'node_modules'
before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - echo "[default]" >> ~/.aws/config
  - echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
  - echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
after_success:
  - npm run aws:upload
